### ISSUE TITLE
JSON-escape trigger strings

### ISSUE THREAD

**Issue by robertklep** [athombv/homey-arduino-library#4]
The following causes a JSON parse issue in the app:

```
Homey.trigger("foo", "\"bar\"");
```

The issue is in `_emit()`, which builds a JSON request body without escaping the contents.

I typically use [`ArduinoJson`](https://github.com/bblanchon/ArduinoJson) to deal with creating JSON strings, but tbh, I'm not sure how to add support for it to a regular Arduino IDE lib (I'm a PlatformIO-user myself, where you can declare dependencies for your library).

If _"Also install ArduinoJson when you want to use this library"_ is good enough, I'd be happy to take a shot at creating a PR.

**Comment by renzenicolai** [comment]
Adding an escape function means even more string manipulation / memory usage and the library is currently hitting the limits of the smaller Arduino boards (Leonardo / Uno) already.

This is probably not going to be fixed, instead I will add a note to the documentation.

**Comment by robertklep** [comment]
@renzenicolai perhaps consider using [`msgpack`](https://github.com/HEADS-project/arduino_msgpack) instead of JSON? Especially on memory-constrained devices, I think msgpack is much more efficient.

**Comment by renzenicolai** [comment]
Won't fix.

As switching to msgpack would require a massive rewrite this option is not available.

Using a proper JSON library would cause the library to become too big for small targets (like the atmega32u4), which is in my opinion a bigger issue than not being able to use certain characters.

A possible solution could be to include an option to use a proper JSON library with escaping features, since implementing this is not possible within the last weeks of my internship I will leave this to the community. (the community could maybe also include msgpack support ;-) )
